[buf]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[java]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[gcloud]
disabled = true

[sudo]
style = "bold green"
symbol = "root "
disabled = false

[cmd_duration]
min_time = 2000
format = "underwent [$duration](bold yellow)"
