# python virtual envs
export WORKON_HOME=~/dev/arch-venvs
# source /usr/bin/virtualenvwrapper_lazy.sh

export VISUAL=/usr/bin/nvim
export EDITOR=/usr/bin/nvim

source $HOME/.k8s_functions.sh
source $HOME/.fw.sh

# aliases
alias k=kubectl
alias mk=minikube
alias dc=docker-compose
# alias vim=nvim
alias y=yarn
alias clip='xsel --clipboard --input'

# PATH
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/go/bin
PATH=$PATH:$HOME/.yarn/bin
PATH=$PATH:$HOME/.cargo/bin
PATH=$PATH:/opt/google-cloud-sdk/bin
PATH=$PATH:${KREW_ROOT:-$HOME/.krew}/bin

