export VISUAL=/usr/bin/nvim
export EDITOR=/usr/bin/nvim
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export ANDROID_HOME=/opt/android-sdk

source $HOME/.k8s_functions.sh

# aliases
alias k=kubectl
alias mk=minikube
alias dc=docker-compose
alias vim=nvim
alias moza=$HOME/go/src/bitbucket.org/nomanini/mz-moza

# PATH
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/go/bin
PATH=$PATH:$HOME/.yarn/bin
PATH=$PATH:$HOME/.local/npm/bin
PATH=$HOME/.cargo/bin:$PATH

