icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#878a8e"

[icons]
icons = "awesome6"

# [[block]]
# block = "custom"
# command = "cat ~/test_i3status"
# watch_files = ["/home/brendan/test_i3status"]

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)($mem_total_used_percents.eng(w:2)) "
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "net"
device = "wlp2s0"
format = " $icon $signal_strength ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
interval = 5

[[block]]
block = "temperature"
interval = 10

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) "

[[block]]
block = "backlight"
device = "intel_backlight"

# [[block]]
# block = "bluetooth"
# mac = "64:03:7F:9B:B1:C8"

[[block]]
block = "sound"
format = " $icon $output_description{ $volume|} "
step_width = 3
headphones_indicator = true
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1f.3.hdmi-stereo" = "HDMI"
"bluez_output.64_03_7F_9B_B1_C8.a2dp-sink" = "🎧"
"bluez_card.F4_B6_88_63_9C_26.1" = "🎧"

[[block]]
block = "battery"
full_threshold = 80
driver = "upower"
device = "DisplayDevice"
format = " $icon $percentage {$time |} $power "

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %m/%d %R') "
