[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#878a8e"

[icons]
name = "awesome"

# [[block]]
# block = "custom"
# command = "cat ~/test_i3status"
# watch_files = ["/home/brendan/test_i3status"]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
icons = true
clickable = true
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "net"
device = "wlp2s0"
format = "{signal_strength} {ssid}"
interval = 5

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "bluetooth"
mac = "64:03:7F:9B:B1:C8"

[[block]]
block = "sound"
format = "{output_name} {volume}"
step_width = 3
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1f.3.hdmi-stereo" = "HDMI"
"bluez_output.64_03_7F_9B_B1_C8.a2dp-sink" = "🎧"

[[block]]
block = "battery"
interval = 10
device = "BAT0"
format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %r"
