[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#878a8e"

[icons]
name = "awesome5"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "custom"
command = "current_env"
interval = 1
# watch_files = ["~/.kube/config"]
json = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
icons = true
clickable = true
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "net"
device = "wlp5s0"
format = "{signal_strength} {ssid}"
interval = 5

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "bluetooth"
mac = "64:03:7F:9B:B1:C8"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "battery"
interval = 10
device = "BAT0"
format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %r"
